project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "JG"

  page-footer:
    left: "&copy; 2025, J.Gravier"
    right: "Built with [Quarto Website](https://quarto.org/docs/websites/)."

  navbar:
    left:
      - href: index.qmd
        text: Home
      
      - href: about.qmd
        text: CV
      
      - href: phd/index.qmd
        text: PhD
        
      - href: publications/index.qmd
        text: Publications

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



